# Generated by Django 5.0 on 2023-12-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0016_alter_scheduledpayment_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'pending')], default='pending', max_length=2)),
                ('persisted', models.BooleanField(default=False)),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('reciever', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payment_Reciever', to='business.account')),
                ('scheduledPayment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentInstallment', to='business.scheduledpayment')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payment_Sender', to='business.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('1', 'accepted'), ('2', 'rejected'), ('3', 'pending')], default='pending', max_length=2)),
                ('persisted', models.BooleanField(default=False)),
                ('date_issued', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentOffer', to='business.offer')),
                ('reciever', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_Reciever', to='business.account')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_Sender', to='business.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
