# Generated by Django 4.2.8 on 2023-12-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_scheduledpayment_duedate'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpayment',
            name='offer',
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loanRequest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentOffer', to='business.loanrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payment_Reciever', to='business.account'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='scheduledPayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentInstallment', to='business.scheduledpayment'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payment_Sender', to='business.account'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_Reciever', to='business.account'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment_Sender', to='business.account'),
        ),
    ]
