# Generated by Django 4.2.8 on 2023-12-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_alter_scheduledpayment_duedate'),
        ('payment', '0002_remove_loanpayment_offer_loanpayment_loanrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='loanRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentRequest', to='business.loanrequest'),
        ),
    ]
