# Generated by Django 5.0 on 2023-12-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthlyPeriod', models.PositiveIntegerField()),
                ('businessFee', models.DecimalField(decimal_places=2, default=3.75, max_digits=15)),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'accepted'), ('3', 'pending')], default='pending', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('borrowerAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_account_requests', to='business.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loanrequest',
            constraint=models.CheckConstraint(check=models.Q(('principle__gt', 0)), name='check positive principle values'),
        ),
        migrations.AddConstraint(
            model_name='loanrequest',
            constraint=models.CheckConstraint(check=models.Q(('businessFee__gte', 0)), name='check positive or zero fee values'),
        ),
    ]
