# Generated by Django 5.0 on 2023-12-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_loanrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='borrowerAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_loan_requests', to='business.account'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='monthlyPeriod',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'funded'), ('3', 'rejected')], default='pending', max_length=2),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestRate', models.DecimalField(decimal_places=4, default=0.15, max_digits=10)),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'accepted'), ('3', 'rejected')], default='pending', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('lenderAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_offers', to='business.account')),
                ('loanRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_request_offers', to='business.loanrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(check=models.Q(('interestRate__gt', 0)), name='check positive interest rate values'),
        ),
    ]
