# Generated by Django 5.0 on 2023-12-16 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_loanrequest_borroweraccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('2', 'funded')], default='pending', max_length=2),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lenderAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_account_offers', to='business.account'),
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'paid'), ('2', 'scheduled'), ('3', 'returned'), ('4', 'waiting')], default='pending', max_length=2)),
                ('paymentDate', models.DateTimeField()),
                ('priority', models.PositiveIntegerField()),
                ('borrowerAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_account_sched_payments', to='business.account')),
                ('lenderAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_account_sched_payments', to='business.account')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.offer')),
            ],
        ),
    ]
