# Generated by Django 5.0 on 2023-12-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_loanrequest_status_alter_offer_lenderaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledpayment',
            name='paymentDate',
        ),
    ]
