# Generated by Django 5.0 on 2023-12-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_scheduledpayment_paymentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpayment',
            name='paymentDate',
            field=models.DateTimeField(null=True),
        ),
    ]
