# Generated by Django 5.0 on 2023-12-17 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.RemoveField(
            model_name='scheduledpayment',
            name='paymentDate',
        ),
        migrations.AddField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 12, 43, 37, 320574)),
        ),
    ]
