# Generated by Django 5.0 on 2023-12-17 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_delete_cat_remove_scheduledpayment_paymentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 12, 44, 24, 449279, tzinfo=datetime.timezone.utc)),
        ),
    ]
