# Generated by Django 5.0 on 2023-12-17 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_scheduledpayment_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lockedBalance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 17, 7, 1, 161279, tzinfo=datetime.timezone.utc)),
        ),
    ]
