# Generated by Django 5.0 on 2023-12-17 18:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_scheduledpayment_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 18, 3, 40, 854131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerSchedPayment', to='business.offer'),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='status',
            field=models.CharField(choices=[('1', 'paid'), ('2', 'scheduled'), ('4', 'waiting')], default='pending', max_length=2),
        ),
    ]
