# Generated by Django 5.0 on 2023-12-17 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_scheduledpayment_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 18, 59, 31, 641329, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='status',
            field=models.CharField(choices=[('1', 'paid'), ('2', 'pending'), ('4', 'waiting')], default='pending', max_length=2),
        ),
    ]
