# Generated by Django 5.0 on 2023-12-17 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_scheduledpayment_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 19, 7, 40, 638731, tzinfo=datetime.timezone.utc)),
        ),
    ]
