# Generated by Django 4.2.8 on 2023-12-17 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_scheduledpayment_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 23, 43, 14, 505815, tzinfo=datetime.timezone.utc)),
        ),
    ]
