# Generated by Django 4.2.8 on 2023-12-18 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_alter_scheduledpayment_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 16, 55, 2, 666945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='loanrequest',
            constraint=models.CheckConstraint(check=models.Q(('monthlyPeriod__gt', 0)), name='check positive monthlyPeriod values'),
        ),
    ]
