# Generated by Django 4.2.8 on 2023-12-18 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_alter_scheduledpayment_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='principle',
            field=models.DecimalField(decimal_places=2, default=6000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='scheduledpayment',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 18, 0, 36, 837531, tzinfo=datetime.timezone.utc)),
        ),
    ]
